### ISSUE TITLE
Tests won't compile with ghc-9.8.2

### ISSUE THREAD

**Issue by GuillaumedeVolpiano** [fumieval/winery#11]
I get a weird ambiguous variable issue, which I can't seem to solve (or understand the cause of)

[1 of 1] Compiling Main             ( test/Spec.hs, /root/github/winery/dist-newstyle/build/x86_64-linux/ghc-9.8.4/winery-1.5/t/spec/build/spec/spec-tmp/Main.o )

test/Spec.hs:195:50: error: [GHC-83865]
    • Couldn't match type: Wear sw0 Subextractor Int
                     with: Subextractor Int
      Expected: Wear Covered Subextractor Int
        Actual: Wear sw0 Subextractor Int
      The type variable ‘sw0’ is ambiguous
    • In a record update at field ‘qux’,
      with type constructor ‘HRecB’
      and data constructor ‘HRec’.
      In the first argument of ‘buildRecordExtractor’, namely
        ‘bextractors {qux = extractField "qux" <|> extractField "oldQux"}’
      In the second argument of ‘($)’, namely
        ‘buildRecordExtractor
           bextractors {qux = extractField "qux" <|> extractField "oldQux"}’
    |
195 |   extractor = fmap bstrip $ buildRecordExtractor bextractors
    |                                                  ^^^^^^^^^^^...
